<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\GamenTrail.ico</ApplicationIcon>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\GamenTrail.ico" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <ProjectReference Include="..\GamenTrail.Core\GamenTrail.Core.csproj" />
    <ProjectReference Include="..\GamenTrail.Platform.Windows\GamenTrail.Platform.Windows.csproj" />
  </ItemGroup>

</Project>
